// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MeanVarWithin
arma::mat MeanVarWithin(const arma::mat& m, const arma::sp_mat& NNmatrix);
RcppExport SEXP _CEIDR_MeanVarWithin(SEXP mSEXP, SEXP NNmatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type NNmatrix(NNmatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(MeanVarWithin(m, NNmatrix));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CEIDR_MeanVarWithin", (DL_FUNC) &_CEIDR_MeanVarWithin, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_CEIDR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
