# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MeanVarWithin <- function(m1, NNmatrix) {
    .Call('_CEIDR_MeanVarWithin', PACKAGE = 'CEIDR', m1, NNmatrix)
}

